@startuml  Use Case 07: การดูรายการผู้เช่าทั้งหมด
skinparam defaultFontName "TH Sarabun New"
title Use Case 07: การดูรายการผู้เช่าทั้งหมด
actor "ผู้ดูแล" as Admin
participant "UI" as UI
participant "Tenant Service" as MS
database "Tenant DB" as DB

Admin -> UI      : เลือกเมนู "รายการผู้เช่า"
activate UI

UI -> MS         : getAllTenants()
activate MS

note right of MS
SELECT name, phone
FROM Tenant
end note
MS -> DB         : เลือกรายการผู้เช่าทั้งหมดจาดฐานข้อมูล
activate DB

DB --> MS        : ส่งรายการผู้เช่าทั้งหมด
deactivate DB

MS --> UI        : แสดงข้อผู้เช่าทั้งหมด\n- ชื่อ-นามสกุล\n- เบอร์โทรศัพท์
deactivate MS
deactivate UI

@enduml