@startuml
skinparam defaultFontName "TH Sarabun New"
title Use Case 06: แก้ไขข้อมูลผู้เช่า
actor "ผู้ดูแล" as Admin
participant "UI" as UI
participant "Tenant Service" as MS
database "Tenant DB" as DB

Admin -> UI    : เลือก "แก้ไข"
UI -> UI       : แสดงฟอร์มแก้ไข (phone, email)

alt ตรวจสอบรูปแบบข้อมูล
    Admin -> UI    : ปรับปรุงข้อมูล\nเบอร์โทรศัพท์\nอีเมล
    UI -> UI       : ตรวจสอบรูปแบบข้อมูล
else รูปแบบข้อมูลผิดพลาด
    UI --> Admin: ข้อมูล ${data} ผิด format กรุณากรอกใหม่อีกครั้ง
end

Admin -> UI        : คลิก "บันทึก"

UI -> MS           : updateTenent()
activate MS
note right of MS
UPDATE Tenant 
SET phone=X, email=X
WHERE tenantId=${tenantId}
end note
MS -> DB           : บันทึกการแก้ไขผู้เช่าลงในฐานข้อมูล
activate DB
DB --> MS          : 200 OK  updateSuccess
deactivate DB
MS --> UI          : แสดงข้อความ "บันทึกข้อมูลเรียบร้อยแล้ว"
deactivate MS
UI -> UI           : กลับไปหน้ารายการผู้เช่า

@enduml
