

@startuml
skinparam defaultFontName "TH Sarabun New"

actor "ผู้ดูแล" as Admin
participant "UI" as UI
participant "Microservice Room" as  MSROOM
database    ROOM    as Room

Admin -> UI  : เลือก "ดูรายละเอียด" ห้อง ${roomId}
activate UI
UI -> MSROOM :findById(roomId) 
activate MSROOM
MSROOM -> Room : SELECT * FROM Room \n WHERE roomId={roomId}
activate Room
Room --> MSROOM: แสดงรายละเอียดห้องพัก ${roomId}
deactivate Room
MSROOM --> UI: แสดงรายละเอียดห้องพัก\n- หมายเลขห้อง\n- ชั้น\n- ค่าเช่าต่อเดือน\n- เฟอร์นิเจอร์ & มูลค่า\n- สถานะ (ว่าง/ถูกเช่า)
deactivate MSROOM
deactivate UI
@enduml

' @startuml
' skinparam defaultFontName "TH Sarabun New"

' actor "ผู้ดูแล" as Admin
' participant "UI" as UI
' participant "Microservice Room" as MSROOM
' database "Room DB" as Room

' Admin -> UI : เลือก "ดูรายละเอียด" ห้อง ${roomId}
' activate UI

' UI -> MSROOM : findById(roomId)
' activate MSROOM

' MSROOM -> Room : SELECT * FROM Room\nWHERE roomId=${roomId}
' activate Room

' Room --> MSROOM : RoomEntity
' deactivate Room

' MSROOM --> UI : RoomDTO\n(รายละเอียดห้องพัก)
' deactivate MSROOM

' UI --> Admin : แสดงรายละเอียดห้องพัก\n- หมายเลขห้อง\n- ชั้น\n- ค่าเช่าต่อเดือน\n- เฟอร์นิเจอร์ & มูลค่า\n- สถานะ (ว่าง/ถูกเช่า)
' deactivate UI

' @enduml

