@startuml use case 11 การอัปโหลดสัญญากระดาษ
title Use Case 11 การอัปโหลดสัญญากระดาษ
skinparam defaultFontName "TH Sarabun New"

actor "ผู้ดูแลระบบ" as Admin
participant "UI" as UI
participant "กล้อง" as Camera

Admin -> UI      : เลือก "อัปโหลดสัญญากระดาษ"
activate UI
UI -> UI: แสดงหน้า "อัปโหลดหนังสือสัญญา"

alt ถ่ายภาพสัญญา
    Admin -> UI  : เลือก "ถ่ายภาพสัญญา"
    UI -> Camera: ส่งคำขอเข้าถึงกล้องบนอุปกรณ์
    activate Camera
    Camera --> Admin: แสดงหน้า "กล้อง"
    deactivate Camera

    Admin -> Camera: ถ่ายภาพสัญญา
    activate Camera

    Camera --> UI: แสดงภาพถ่าย
    deactivate Camera
    Admin -> UI: ยืนยันภาพถ่าย

else อัปโหลดเอกสารจากเครื่อง
    Admin -> UI      : เลือกไฟล์เอกสารหนังสือสัญญาจากเครื่อง

    alt ประเภทไฟล์ถูกต้อง
        UI -> UI : แสดงไฟล์เอกสาร
        Admin -> UI: ยืนยันไฟล์เอกสาร
    else ไฟล์ไม่รองรับ
        UI->UI : แสดงข้อความ "กรุณาอัปโหลดไฟล์อีกครั้ง"
    end

end
deactivate UI
@enduml


