@startuml
skinparam defaultFontName "TH Sarabun New"
title Use Case 05: ลงทะเบียนผู้เช่า
actor "ผู้ดูแล" as Admin
participant "UI" as UI
participant "Tenant Service" as MS
database "Tenant DB" as DB


Admin -> UI: เลือก "ลงทะเบียนผู้เช่า"
activate UI

UI --> UI       : แสดงฟอร์มลงทะเบียนผู้เช่า
alt กรอกข้อมูล
    Admin -> UI: กรอกข้อมูล ชื่อ-นามสกุล, เบอร์โทรศัพท์, อีเมลล์ \n วันเกิด, บัตรประชาชน, ข้อมูลติดต่ออื่น ๆ
    UI --> UI       : ตรวจสอบรูปแบบข้อมูล \nเบอร์โทรศัพท์ \nอีเมลล์ \nบัตรประชาชน
else รูปแบบข้อมูลผิดพลาด
    UI --> Admin: ข้อมูล ${data} ผิด format กรุณากรอกใหม่อีกครั้ง
end
Admin -> UI: เลือก "บันทึก"
UI -> MS: createdTenant()

alt ตรวจสอบข้อมูลผู้เช่า
    activate MS

    note right of MS
    INSERT INTO Tenant ( tanentThaiID, ... )
    VALUES(tanentThaiID, ...)
    end note
    MS -> DB: เพิ่มข้อมูลผู้เช่าลงในฐานข้อมูล
    activate DB
    DB --> MS: บันทึกการเพิ่มสำเสร็จ (201, created)
    deactivate DB

    MS --> UI: ลงทะเบียนผู้เช่าสำเร็จ
else ถ้าขอมูลของผู้เช่ามีอยู่ในระบบ insert tanentThaiID = DB tanentThaiID
    DB --> MS: Error Duplicate Tenent
    MS --> UI: ผู้เช่านี้มีอยู่ในระบบแล้ว
end
@enduml