@startuml
skinparam defaultFontName "TH Sarabun New"
title Use Case 04: แก้ไขข้อมูลห้องพัก
actor "ผู้ดูแล" as Admin
participant "UI" as UI
participant "RoomService" as MSROOM
database "Room DB" as RoomDB


Admin -> UI      : เลือก "แก้ไข"
activate UI

UI --> UI       : แสดงฟอร์มแก้ไขห้องพัก

Admin -> UI      : ปรับอัตราค่าเช่า หรือ สถานะห้องพัก
UI --> UI       : แสดงข้อมูลที่แก้ไข

Admin -> UI      : เลือก "บันทึก"
UI -> MSROOM    : updateRoom(roomId, newPrice, newStatus)
activate MSROOM


note right of  MSROOM
UPDATE Room
SET roomPrice=newPrice, status=newStatus
WHERE roomId=${roomId}
end note
MSROOM -> RoomDB: บันทึกข้อมูลใหม่
activate RoomDB


RoomDB --> MSROOM: updateSuccess
deactivate RoomDB

MSROOM --> UI    : แสดงข้อความ "บันทึกข้อมูลเรียบร้อยแล้ว"
MSROOM --> UI    : แสดงรายการห้องพักทั้งหมด\n(Room Number, Monthly Rent, Status)

deactivate MSROOM
deactivate UI

@enduml