@startuml Use Case 07: การดูรายละเอียดผู้เช่า
skinparam defaultFontName "TH Sarabun New"
title Use Case 07: การดูรายละเอียดผู้เช่า

actor "ผู้ดูแล" as Admin
participant "UI" as UI
participant "Tenant Microservice" as MS
database "Tenant DB" as DB



Admin -> UI      : เลือก "ดูรายละเอียด" ผู้เช่า ${tenantId}
activate UI

UI -> MS         : getTenantById(tenantId)
activate MS

note right of MS
SELECT * FROM Tenant
WHERE tenantId=${tenantId}
end note
MS -> DB         : เลือกรายละเอียดผู้เช่าจากในฐานข้อมูล
activate DB

DB --> MS        : ส่งข้อมูลผู้เช่าที่ค้นพบ
deactivate DB

MS --> UI        : แสดงรายละเอียดผู้เช่า\n- ชื่อ-นามสกุล\n- เบอร์โทรศัพท์\n- อีเมล\n- วันเกิด\n- บัตรประชาชน\n- ข้อมูลติดต่ออื่น ๆ

deactivate MS
deactivate UI

@enduml
