@startuml Use Case 01: การแสดงรายการห้องพักทั้งหมด
title Use Case 01: การแสดงรายการห้องพักทั้งหมด
skinparam defaultFontName "TH Sarabun New"

actor      "ผู้ดูแล"       as  Admin
participant "UI" as  UI
participant "RoomdService" as  Model
database    ROOM    as Room

Admin -> UI : เลือก "รายการห้องพัก"
activate UI
UI -> Model: getAllRooms()
activate Model
Model -> Room:ค้นหาห้องพักในฐานข้อมูล
note right of Model
    SELECT roomNumber,
    roomPrice, status
    FROM Room
end note
activate Room
Room --> Model: ข้อมูลห้องพักทั้งหมด
deactivate Room
Model --> UI: แสดงตารางห้องพักทั้งหมด \n(Room Number, Monthly Rent, Status)
deactivate Model