@startuml Use Case 02: ดูรายละเอียดห้องพัก
skinparam defaultFontName "TH Sarabun New"
title Use Case 02: ดูรายละเอียดห้องพัก
actor "ผู้ดูแล" as Admin
participant "UI" as UI
participant "RoomService" as  MSROOM
database    ROOM    as Room

Admin -> UI  : เลือก "ดูรายละเอียด" ห้อง ${roomId}
activate UI
UI -> MSROOM :findById(roomId)
activate MSROOM
MSROOM -> Room : ค้นหารายละเอียดห้องพักในฐานข้อมูล

note right of MSROOM
SELECT * FROM Room  WHERE 
roomId={roomId}
end note

activate Room
Room --> MSROOM: แสดงรายละเอียดห้องพัก ${roomId}
deactivate Room
MSROOM --> UI: แสดงรายละเอียดห้องพัก\n- หมายเลขห้อง\n- ชั้น\n- ค่าเช่าต่อเดือน\n- เฟอร์นิเจอร์ & มูลค่า\n- สถานะ (ว่าง/ถูกเช่า)
deactivate MSROOM
deactivate UI
@enduml
