@startuml
skinparam defaultFontName "TH Sarabun New"
' participant Participant as Foo
' actor       Actor       as Foo1
' boundary    Boundary    as Foo2
' control     Control     as Foo3
' entity      Entity      as Foo4
' database    Database    as Foo5
' collections Collections as Foo6
' queue       Queue       as Foo7


actor      "ผู้ดูแล"       as  Admin
participant "UI" as  UI
participant "Roomd Service" as  Model
database    ROOM    as Room

Admin -> UI : เลือก "รายการห้องพัก"
activate UI
UI -> Model: getAllRooms()
activate Model
Model -> Room:ค้นหาห้องพักในฐานข้อมูล
note right of Model
SELECT roomNumber, 
roomPrice, status
FROM Room
end note
activate Room
Room --> Model: ข้อมูลห้องพักทั้งหมด
deactivate Room
Model --> UI: แสดงตารางห้องพักทั้งหมด \n(Room Number, Monthly Rent, Status)
deactivate Model